name: kwolfe
favicon: null
layout_spectrum: 0.36351016466505826
typography_spectrum: 0.6439022165723145
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0C8C8'
    - '#000000'
    - '#807860'
    - '#000000'
    - '#000000'
  brandStrength: 0.9102870339993387
  lightness: 0.375
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
