name: kwolfe
favicon: null
layout_spectrum: 0.36351016466505826
typography_spectrum: 0.6439022165723145
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9102870339993387
  lightness: 0.6952813928946853
  saturation: 0.8626406162511557
  rhythmicContrast: 0.22154006361961365
purpose: []
